### ISSUE TITLE
When can we see the code of PolarBEV?

### ISSUE THREAD

**Issue by xuxiaoxxxx** [SuperZ-Liu/PolarBEV#1]

**Comment by SuperZ-Liu** [comment]
> _No description provided._
Thanks for your interest at our work. The code will be released at Sep.

**Comment by xuxiaoxxxx** [comment]
Thank you for your reply

**Comment by xuxiaoxxxx** [comment]
I'm very interested in this paper, and after I read this paper I have some questions.
First, how can we iterate  to update query embedding _q_(mentioned in 3.3)? 
Second, after we get the image features, how can we use it? concatenate with previous one?
I would appreciate it if you could draw a simple network framework, I think it will help me understand this paper better.
![image](https://user-images.githubusercontent.com/55653936/181180590-ac7dcf57-58ca-42ef-807a-6ba4f91e97ee.png)

**Comment by SuperZ-Liu** [comment]
> I'm very interested in this paper, and after I read this paper I have some questions. First, how can we iterate to update query embedding _q_(mentioned in 3.3)? Second, after we get the image features, how can we use it? concatenate with previous one? I would appreciate it if you could draw a simple network framework, I think it will help me understand this paper better. ![image](https://user-images.githubusercontent.com/55653936/181180590-ac7dcf57-58ca-42ef-807a-6ba4f91e97ee.png)

Sorry for the late reply. The query embedding $q$ are updated by sampling the 2D image features with the 2D-to-3D Feature Transformation.

**Comment by Live-1** [comment]
HI, I also interested in your work. According to your description, I draw a simple network framework. Can you help me check if it is correct? 
![image](https://user-images.githubusercontent.com/110208840/181665743-886fae83-beb8-44cf-957d-12dfc4d741b6.png)

**Comment by SuperZ-Liu** [comment]
> HI, I also interested in your work. According to your description, I draw a simple network framework. Can you help me check if it is correct? ![image](https://user-images.githubusercontent.com/110208840/181665743-886fae83-beb8-44cf-957d-12dfc4d741b6.png)

Yes, it is almost right except for missing the Ring Convolution after the transformation and iterating the whole process several times.

**Comment by Live-1** [comment]
I get it, thank you for your reply!
