### ISSUE TITLE
hi, when will the code be released?

### ISSUE THREAD

**Issue by lizechng** [SuperZ-Liu/PolarBEV#2]
Hi，I am very interested in your excellent work. When will you be able to open source the complete code?
or, could u give a more detailed description about the 

> 3.2 Polar Rasterization and Rearrangement

The multi-view images are passed to a shared CNN block to extract features, and the extracted features, i think, may be HxWxC.
How do u transform the extracted image features into Polar BEV?

look forward to your advise.

**Comment by SuperZ-Liu** [comment]
The code is being arranged and will be released this week or next week. As for the section 3.2, the bev features is first inited with query embedding and rearranged to the array-like rectangular representation. The transformation from image view to bev is described in section 3.4. we get each polar grid features by sampling features from the correspoding image features with the projected points on each image view.

**Comment by lizechng** [comment]
Thx!
